-- Sync services + in-salon brochure menu from docs/familysalonfiles/menu_brochure.jpeg
UPDATE services SET is_active = 0;
UPDATE services SET category = 'facials' WHERE category = 'skin';
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Kids Hair Cut', 'hair', NULL, 30, 13.99, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Men''s Hair Cut', 'hair', NULL, 30, 15.99, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Women''s Hair Cut', 'hair', NULL, 45, 25, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Cut & Style', 'hair', NULL, 60, 30, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Shampoo & Dry', 'hair', NULL, 30, 15, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Blow Dry', 'hair', NULL, 45, 25, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Hair Curling', 'hair', NULL, 60, 35, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Hair Flat Iron', 'hair', NULL, 60, 35, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Roller Set', 'hair', NULL, 60, 50, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Hair Up Do', 'hair', NULL, 60, 50, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Deep Conditioning Treatment', 'hair', NULL, 45, 30, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Hot Oil Treatment', 'hair', NULL, 30, 15, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Hair Protein Treatment', 'hair', NULL, 45, 35, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Men''s Hair Color', 'hair', NULL, 90, 40, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Women''s Hair Color', 'hair', NULL, 120, 60, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Hair Color Retouch', 'hair', NULL, 90, 40, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Highlights Cap or Foil', 'hair', NULL, 150, 95, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Partial Highlights', 'hair', NULL, 120, 80, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Toner', 'hair', NULL, 30, 25, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Henna Treatments', 'hair', NULL, 60, 35, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Perm', 'hair', NULL, 120, 95, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Permanent Straightening', 'hair', NULL, 180, 250, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Keratin Treatment', 'hair', NULL, 150, 200, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Manicure', 'nails', NULL, 45, 25, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Pedicure', 'nails', NULL, 60, 35, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('French Manicure', 'nails', NULL, 50, 30, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Paraffin Manicure', 'nails', NULL, 55, 35, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Shellac Manicure', 'nails', NULL, 60, 30, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Nails Shape with Polish', 'nails', NULL, 20, 10, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Eyebrow Threading', 'threading', NULL, 15, 10, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Upper Lip', 'threading', NULL, 10, 5, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Chin', 'threading', NULL, 10, 5, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Forehead', 'threading', NULL, 10, 8, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Side Burn', 'threading', NULL, 10, 8, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Full Face', 'threading', NULL, 30, 35, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Eyebrows', 'waxing', NULL, 15, 10, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Forehead', 'waxing', NULL, 10, 5, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Upper Lip', 'waxing', NULL, 10, 4, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Chin', 'waxing', NULL, 10, 8, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Side Burn', 'waxing', NULL, 15, 10, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Neck', 'waxing', NULL, 10, 6, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Nose Inside', 'waxing', NULL, 10, 7, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Full Face', 'waxing', NULL, 30, 35, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Full Arms', 'waxing', NULL, 45, 35, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Half Arms', 'waxing', NULL, 30, 25, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Under Arms', 'waxing', NULL, 20, 15, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Full Legs', 'waxing', NULL, 45, 35, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Half Legs', 'waxing', NULL, 30, 25, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Full Back', 'waxing', NULL, 40, 30, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Half Back', 'waxing', NULL, 30, 25, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Belly', 'waxing', NULL, 20, 15, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Brazilian', 'waxing', NULL, 45, 40, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Full Body', 'waxing', NULL, 120, 150, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Individual Lashes', 'lashes', NULL, 60, 35, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Strip Lashes', 'lashes', NULL, 30, 25, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Eyebrow Tinting', 'lashes', NULL, 20, 15, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Diamond Facial', 'facials', NULL, 75, 60, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Antitan Facial', 'facials', NULL, 75, 55, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Gold Facial', 'facials', NULL, 75, 55, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Anti Aging Facial', 'facials', NULL, 75, 50, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Acne Facial', 'facials', NULL, 60, 45, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Silver Facial', 'facials', NULL, 60, 45, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Pearl Facial', 'facials', NULL, 75, 50, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Oxygen Facial', 'facials', NULL, 75, 55, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Glow Facial', 'facials', NULL, 60, 45, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Fruit Facial', 'facials', NULL, 60, 45, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Herbal Facial', 'facials', NULL, 90, 75, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Gentleman''s Facial', 'facials', NULL, 75, 50, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Bleach Face & Neck', 'facials', NULL, 45, 35, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Deep Cleansing', 'facials', NULL, 45, 35, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Hydrafacial', 'facials', NULL, 90, 100, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Body Massage (1 hr)', 'wellness', NULL, 60, 80, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Body Massage (30 min)', 'wellness', NULL, 30, 50, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Back Polish', 'wellness', NULL, 45, 40, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Full Body Polish', 'wellness', NULL, 75, 80, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Party Make-Up', 'makeup', NULL, 90, 70, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Engagement & Reception Make-Up', 'makeup', NULL, 120, 100, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Bridal Make-Up', 'makeup', NULL, 180, 200, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Saree Draping', 'makeup', NULL, 30, 35, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Duppata Setting', 'makeup', NULL, 20, 25, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Henna per Hand', 'henna', NULL, 45, 20, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Front & Back Henna', 'henna', NULL, 60, 35, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Bridal Henna', 'henna', NULL, 180, 200, 'request', 1);
INSERT INTO services (name, category, description, duration_minutes, price, booking_type, is_active) VALUES ('Engagement or Reception Henna', 'henna', NULL, 120, 150, 'request', 1);
